### PR TITLE
Add HTTPClient configure option to set the default http.Client in use - fixes #72

### LINKED ISSUE #72: 支持把http client开放出来，让用户配置
［期望］
你好，我们需要oss client把http client开放出来，支持自定义配置。
［定位］
位置如下：
https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/conn.go#L58

### PR DESCRIPTION
**Pull request by ncw**
Add HTTPClient configure option to set the default http.Client in use

### CODE REVIEW

**Comment by ncw** [comment]
I changed my mind and made an `HTTPClient` option to supply an `http.Client` which is more usual for this kind of library (eg it is [how Amazon do it](https://godoc.org/github.com/aws/aws-sdk-go/aws#Config.WithHTTPClient) with their S3 go SDK).

I've also added some tests.

I'll now sign the CLA.

**Comment by ncw** [comment]
The build appears to be broken for reasons not to do with my PR :-(

**Comment by ncw** [comment]
Is there interest in merging this?  I need it for [rclone](https://rclone.org) support?

I've updated the PR so it merges cleanly.

**Comment by fd0** [comment]
Hey @baiyubin, is there anything we can do to get this merged?

**Comment by ncw** [comment]
I rebased this on master so it is mergeable.

It has a couple of whitespace changes where `go fmt`  stripped whitespace off the end of lines - I'll get rid of those if that is a problem.

**Comment by hangzws** [comment]
hi, nick, thanks for this pr, we will fix it.

**Comment by ncw** [comment]
It looks like this was fixed in https://github.com/aliyun/aliyun-oss-go-sdk/commit/34e27f16 - thank you

**Pull request closed without merging**
